@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYjlkYzUxMS00NGM4LTQxMjUtYWI0Ni0xMmM3ZmEyNzAwYTIiLCJpYXQiOjE3NzEwMTE3NjUsImV4cCI6MTc3MTYxNjU2NX0.5tfKvnM5POH9Z-BD7XHI_ngFbz4LPgyss_RjWFJ8zrY



### 1. Solicitar Magic Link
# @name magicLink
POST {{baseUrl}}/api/auth/magic-link
Content-Type: application/json

{
  "email": "user@user.com"
}

### GET /user - Listar usuários
GET {{baseUrl}}/api/users
Authorization: Bearer {{accessToken}}

### GET /user - Listar com paginacao
GET {{baseUrl}}/api/user?limit=10
Authorization: Bearer {{accessToken}}

### GET /user - Buscar por email
GET {{baseUrl}}/api/users?email=user@user.com
Authorization: Bearer {{accessToken}}


### GET /user/{id} - Buscar usuario por ID
GET {{baseUrl}}/api/user/1598cc56-e459-4bf5-ad85-3c67f8a64538
Authorization: Bearer {{accessToken}}

### PUT /user/{id} - Atualizar dados do usuario
PUT {{baseUrl}}/api/user/1598cc56-e459-4bf5-ad85-3c67f8a64538
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "1598cc56-e459-4bf5-ad85-3c67f8a64538",
  "version": 2,
  "createdAt": "2024-01-01T00:00:00.000Z",
  "updatedAt": "2024-01-01T00:00:00.000Z",
  "email": "teste@exemplo.com",
  "nickname": "deh",
  "name": "Meu Nome",
  "bio": "Minha bio"
}

### DELETE /user/{id} - Deletar usuario (so pode deletar a si mesmo)
DELETE {{baseUrl}}/api/user/1598cc56-e459-4bf5-ad85-3c67f8a64538
Authorization: Bearer {{accessToken}}

